Move to ember-cli@6.7.0

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,20 +8,21 @@ on:
   pull_request: {}
 
 concurrency:
-   group: ci-${{ github.head_ref || github.ref }}
-   cancel-in-progress: true
+  group: ci-${{ github.head_ref || github.ref }}
+  cancel-in-progress: true
 
 jobs:
   test:
     name: "Tests"
     runs-on: ubuntu-latest
+    timeout-minutes: 10
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Install Node
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
-          node-version: 12.x
+          node-version: 18
           cache: npm
       - name: Install Dependencies
         run: npm ci
@@ -33,12 +34,13 @@ jobs:
   floating:
     name: "Floating Dependencies"
     runs-on: ubuntu-latest
+    timeout-minutes: 10
 
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
         with:
-          node-version: 12.x
+          node-version: 18
           cache: npm
       - name: Install Dependencies
         run: npm install --no-shrinkwrap
@@ -48,29 +50,59 @@ jobs:
   try-scenarios:
     name: ${{ matrix.try-scenario }}
     runs-on: ubuntu-latest
-    needs: 'test'
+    needs: "test"
+    timeout-minutes: 10
 
     strategy:
       fail-fast: false
       matrix:
         try-scenario:
-          - ember-lts-3.24
-          - ember-lts-3.28
+          - ember-lts-5.4
+          - ember-lts-5.8
+          - ember-lts-5.12
+          - ember-lts-6.4
           - ember-release
           - ember-beta
           - ember-canary
-          - ember-classic
           - embroider-safe
           - embroider-optimized
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Install Node
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
-          node-version: 12.x
+          node-version: 18
           cache: npm
       - name: Install Dependencies
         run: npm ci
       - name: Run Tests
         run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
+
+  validate-success:
+    needs:
+      ["try-scenarios"]
+    runs-on: ubuntu-latest
+    outputs:
+      success: ${{ steps.set-output.outputs.success }}
+    steps:
+      - id: set-output
+        run: echo "success=true" >> $GITHUB_OUTPUT
+
+  notify-success:
+    name: CI pipeline succeeded
+    needs: ["validate-success"]
+    if: always() # Always run, so we never skip this required check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Note Pipeline Passed
+        run: |
+          msgPrefix="Pipeline #${{ github.run_id }} finished"
+          passed="${{ needs.validate-success.outputs.success }}"
+          if [[ "$passed" == "true" ]]; then
+            echo "${msgPrefix}, PR passed all tests."
+            exit 0
+          else
+            echo "${msgPrefix}, but with failures. Check left sidebar summary to see which jobs failed."
+            exit 1
+          fi
